#!/usr/bin/env bash
# Phase 6 invariant verifier (codex HIGH-7 + HIGH-8 closure).
# Called by :backend:api:loadtestVerify (Gradle Exec). Invoke only after:
#   1) docker compose up -d --wait
#   2) psql -f loadtest/scripts/seed-tenants.sql
#   3) k6 run loadtest/scripts/golden-path.js
#   4) loadtest/scripts/wait-for-worker-drain.sh
#   5) docker compose logs ... > loadtest/run/run.log
set -euo pipefail

DB_HOST="${LOADTEST_DB_HOST:-localhost}"
DB_PORT="${LOADTEST_DB_PORT:-15433}"
DB_NAME="${LOADTEST_DB_NAME:-zeromail}"
DB_USER="${LOADTEST_DB_USER:-zeromail}"
DB_PASSWORD="${LOADTEST_DB_PASSWORD:-zeromail}"
RUN_LOG="${LOADTEST_RUN_LOG:-loadtest/run/run.log}"
RESULT_FILE="${LOADTEST_RESULT_FILE:-.planning/phases/06-polish-casa-verified-launch/06-LOAD-TEST-RESULT.md}"

export PGPASSWORD="$DB_PASSWORD"

psql_query() {
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc "$1"
}

echo "event=loadtest_verify_start"

cross_tenant_count=$(psql_query "SELECT COUNT(*) FROM triage_audit WHERE tenant_id NOT IN (SELECT tenant_id FROM loadtest_tenant)")
if [[ "$cross_tenant_count" -ne 0 ]]; then
    echo "event=invariant_a_FAIL cross_tenant_count=$cross_tenant_count" >&2
    exit 1
fi
echo "event=invariant_a_PASS"

double_finalize=$(psql_query "
  SELECT COUNT(*) FROM (
    SELECT ref_id
    FROM credit_ledger_entry
    WHERE ref_type = 'RESERVATION'
      AND tenant_id IN (SELECT tenant_id FROM loadtest_tenant)
    GROUP BY ref_id
    HAVING COUNT(*) FILTER (WHERE kind = 'SETTLE') > 1
        OR COUNT(*) FILTER (WHERE kind = 'RELEASE') > 1
        OR (COUNT(*) FILTER (WHERE kind = 'SETTLE') > 0 AND COUNT(*) FILTER (WHERE kind = 'RELEASE') > 0)
  ) AS bad
")
if [[ "$double_finalize" -ne 0 ]]; then
    echo "event=invariant_b1_FAIL double_finalize=$double_finalize" >&2
    exit 1
fi
echo "event=invariant_b1_PASS"

negative_balance_tenants=$(psql_query "
  SELECT COUNT(*) FROM (
    SELECT tenant_id
    FROM credit_ledger_entry
    WHERE tenant_id IN (SELECT tenant_id FROM loadtest_tenant)
    GROUP BY tenant_id
    HAVING SUM(amount_credits) < 0
  ) AS underwater
")
if [[ "$negative_balance_tenants" -ne 0 ]]; then
    echo "event=invariant_b2_FAIL negative_balance_tenants=$negative_balance_tenants" >&2
    exit 1
fi
echo "event=invariant_b2_PASS"

if [[ ! -f "$RUN_LOG" ]]; then
    echo "event=invariant_c_PRE_FAIL missing=$RUN_LOG" >&2
    exit 1
fi
bleed_lines=$(grep -cE 'email_body|prompt|completion|raw_html' "$RUN_LOG" || true)
if [[ "$bleed_lines" -gt 0 ]]; then
    echo "event=invariant_c_FAIL bleed_lines=$bleed_lines" >&2
    grep -nE 'email_body|prompt|completion|raw_html' "$RUN_LOG" | head -5 >&2
    exit 1
fi
echo "event=invariant_c_PASS"

mkdir -p "$(dirname "$RESULT_FILE")"
cat > "$RESULT_FILE" <<EOF
# Load-Test Result - $(date -u +%Y-%m-%dT%H:%M:%SZ)

- Invariant (a) cross-tenant audit: PASS (0 rows whose tenant_id is outside the loadtest_tenant allow-list)
- Invariant (b1) no double-finalize: PASS (0 RESERVATION ref_ids with >1 SETTLE, >1 RELEASE, or both)
- Invariant (b2) per-tenant non-negative balance: PASS (every loadtest tenant ends with SUM(amount_credits) >= 0)
- Invariant (c) log-bleed regex: PASS (0 lines matching email_body|prompt|completion|raw_html)

*Generated by loadtest/scripts/loadtest-verify.sh AFTER wait-for-worker-drain.sh confirmed pubsub_delivery PENDING == 0 (MED-3). Source: \`$RUN_LOG\` + psql to \`$DB_HOST:$DB_PORT/$DB_NAME\`.*
EOF

echo "event=loadtest_verify_complete result_file=$RESULT_FILE"
