// Phase 6 golden-path launch invariant (SPEC AC #1):
// sign-up -> connect Gmail -> enable template rule -> Pub/Sub push -> triage -> undo
// -> draft -> analytics.
// Runs under the `e2e-stub` Spring profile from Plan 06-01. The Pub/Sub leg uses
// request.fetch() per D-08.
//
// codex cycle-2 HIGH-3 closure: this spec authenticates via the e2e-stub
// seed-session endpoint, which creates a real User and Tenant row and returns the
// tenantId. The X-Test-Subject and X-Test-Email headers are set on both the API
// context and the browser context so Plan 06-01's E2eStubAuthConfig chain
// authenticates real backend requests before the production OAuth2 chain.
//
// codex cycle-2 HIGH-4 closure: Step 8 asserts the saved-draft body via
// GET /api/test/e2e-stub/drafts?messageId={id} and confirms the body matches
// E2eStubChatModel's canned text.
//
// HIGH-2: seed-message body must match the SeedMessageRequest record exactly:
// { tenantId, messageId, threadId, from, subject, body }. Sync both sides if
// either changes.

import { expect, request as playwrightRequest, test, type Locator } from '@playwright/test';

import { expectAppShellChrome, expectNoHorizontalOverflow } from './chrome-test-utils';

const BACKEND_BASE_URL = 'http://localhost:8080';
const FRONTEND_BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:3000';
const SEED_MESSAGE_ID = 'gmail-msg-1';
const SEED_THREAD_ID = 'thread-1';
const SEED_FROM = 'billing@stripe.com';
const SEED_SUBJECT = 'Receipt for Zero Mail';
const SEED_BODY = 'Hello tester';
const EXPECTED_DRAFT_TEXT = 'Hello tester — generated by E2eStubChatModel';

type SeedSessionResponse = {
  tenantId: string;
  googleSubject: string;
  email: string;
  sessionCookieName: string;
  sessionCookieValue: string;
};

type AuditEntryResponse = {
  auditId?: string;
  gmailThreadId?: string;
  gmailMessageId?: string;
  ruleName?: string;
  action?: string;
  decisionState?: string;
};

type AuditListResponse = {
  items?: AuditEntryResponse[];
};

type DraftResponse = {
  draftId?: string;
  messageId?: string;
  body?: string;
};

test.describe.configure({ mode: 'serial' });

test.describe('Launch golden path', () => {
  test('full v1 journey', async ({ browser }) => {
    test.setTimeout(120_000);

    let tenantId = '';
    let googleSubject = '';
    let email = '';
    let sessionCookieName = 'ZEROMAIL_SESSION';
    let sessionCookieValue = '';
    const seedRunId = crypto.randomUUID();
    const seedMessageId = `${SEED_MESSAGE_ID}-${seedRunId}`;
    const seedThreadId = `${SEED_THREAD_ID}-${seedRunId}`;

    await test.step('0. reset e2e-stub state and seed session', async () => {
      const bootstrap = await playwrightRequest.newContext({ baseURL: BACKEND_BASE_URL });
      try {
        const resetReady = expect.poll(
          async () => {
            const response = await bootstrap.post('/api/test/e2e-stub/reset');
            return response.ok();
          },
          {
            intervals: [500, 500, 500],
            timeout: 3000,
            message: 'e2e-stub reset endpoint did not become ready',
          },
        );
        await resetReady.toBeTruthy();

        const sessionResponse = await bootstrap.post('/api/test/e2e-stub/seed-session');
        expect(sessionResponse.ok()).toBeTruthy();
        const sessionBody = (await sessionResponse.json()) as SeedSessionResponse;
        expect(sessionBody.tenantId).toMatch(
          /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
        );
        tenantId = sessionBody.tenantId;
        googleSubject = sessionBody.googleSubject;
        email = sessionBody.email;
        sessionCookieName = sessionBody.sessionCookieName || sessionCookieName;
        sessionCookieValue = sessionBody.sessionCookieValue;
      } finally {
        await bootstrap.dispose();
      }
    });

    const authHeaders = { 'X-Test-Subject': googleSubject, 'X-Test-Email': email };
    const request = await playwrightRequest.newContext({
      baseURL: BACKEND_BASE_URL,
      extraHTTPHeaders: authHeaders,
    });
    const context = await browser.newContext({
      extraHTTPHeaders: authHeaders,
    });
    await context.addCookies([
      {
        name: sessionCookieName,
        value: sessionCookieValue,
        domain: 'localhost',
        path: '/',
        httpOnly: true,
        sameSite: 'Lax',
        secure: false,
      },
      {
        name: 'NEXT_LOCALE',
        value: 'en',
        domain: 'localhost',
        path: '/',
        sameSite: 'Lax',
        secure: false,
      },
    ]);
    const page = await context.newPage();

    try {
      await test.step('1. land on dashboard with header-authenticated backend', async () => {
        await page.goto(`${FRONTEND_BASE_URL}/dashboard`, { waitUntil: 'domcontentloaded' });
        await expectAppShellChrome(page, { sidebarVisible: true });
      });

      await test.step('2. confirm Gmail connection from e2e-stub provisioning', async () => {
        await page.goto(`${FRONTEND_BASE_URL}/onboarding/gmail-connect`, {
          waitUntil: 'domcontentloaded',
        });
        await expect(page.getByText(email)).toBeVisible({ timeout: 15_000 });
        await expect(page.getByText('Connected').first()).toBeVisible();
      });

      await test.step('3. enable template rule from gallery', async () => {
        await page.goto(`${FRONTEND_BASE_URL}/rules`, { waitUntil: 'domcontentloaded' });
        await expect(
          page.getByRole('heading', { name: 'Automation rules', exact: true }),
        ).toBeVisible();

        const archiveRule = page.getByRole('heading', { name: 'Archive receipts' }).first();
        if (!(await waitForLocatorVisible(archiveRule, 5000))) {
          await page.getByRole('button', { name: 'Browse templates' }).click();
          await expect(page.getByRole('dialog', { name: 'Starter templates' })).toBeVisible();
          await page.getByRole('button', { name: 'Use starter rule' }).first().click();
          await expect(archiveRule).toBeVisible({ timeout: 15_000 });
        }

        const closeTemplateDialogButton = page.getByRole('button', { name: 'Close' });
        if (await locatorIsVisible(closeTemplateDialogButton)) {
          await closeTemplateDialogButton.click();
        }

        const disableRuleButton = page.getByRole('button', { name: 'Disable rule' }).last();
        if (!(await locatorIsVisible(disableRuleButton))) {
          const previewRuleButton = page.getByRole('button', { name: 'Preview rule' }).last();
          await expect(previewRuleButton).toBeEnabled({ timeout: 15_000 });
          await previewRuleButton.click();
          const enableRuleButton = page.getByRole('button', { name: 'Enable rule' }).last();
          await expect(enableRuleButton).toBeEnabled({ timeout: 15_000 });
          await enableRuleButton.click();
        }

        await expect(page.getByText('Enabled').first()).toBeVisible();

        const optInResponse = await request.post(
          `/api/triage/sender-safety-net/${encodeURIComponent(SEED_FROM)}/opt-in`,
        );
        expect(optInResponse.ok()).toBeTruthy();
        const optInBody = (await optInResponse.json()) as {
          senderEmail?: string;
          optedIn?: boolean;
        };
        expect(optInBody).toMatchObject({
          senderEmail: SEED_FROM,
          optedIn: true,
        });
      });

      await test.step('4. seed Gmail message and push Pub/Sub envelope', async () => {
        const seedResponse = await request.post('/api/test/e2e-stub/seed-message', {
          data: {
            tenantId,
            messageId: seedMessageId,
            threadId: seedThreadId,
            from: SEED_FROM,
            subject: SEED_SUBJECT,
            body: SEED_BODY,
          },
          headers: { 'Content-Type': 'application/json' },
        });
        expect(seedResponse.status()).toBe(204);

        const historyId = numericHistoryIdFromUUID(crypto.randomUUID());
        const pubSubMessageId = crypto.randomUUID();
        const data = Buffer.from(JSON.stringify({ emailAddress: email, historyId })).toString(
          'base64',
        );
        const envelope = {
          message: {
            data,
            messageId: pubSubMessageId,
            publishTime: new Date().toISOString(),
          },
          subscription: 'projects/e2e-stub/subscriptions/sub',
        };
        const pushResponse = await request.fetch('/internal/pubsub/gmail', {
          method: 'POST',
          data: envelope,
          headers: {
            Authorization: 'Bearer e2e-stub-token',
            'Content-Type': 'application/json',
          },
        });
        expect(pushResponse.ok()).toBeTruthy();

        const processResponse = await request.post('/api/test/e2e-stub/process-deliveries');
        expect(processResponse.status()).toBe(204);
      });

      await test.step('5. observe triage action in audit log', async () => {
        const auditApplied = expect.poll(
          async () => {
            const response = await request.get('/api/triage/audit');
            if (!response.ok()) return '';
            const auditList = (await response.json()) as AuditListResponse;
            const matchingEntry = (auditList.items ?? []).find(
              (entry) =>
                entry.gmailMessageId === seedMessageId &&
                entry.gmailThreadId === seedThreadId &&
                entry.ruleName === 'Archive receipts' &&
                entry.decisionState === 'APPLIED',
            );
            return matchingEntry
              ? `${matchingEntry.ruleName}:${matchingEntry.action}:${matchingEntry.decisionState}`
              : '';
          },
          {
            intervals: [500, 1000, 2000, 3000, 5000],
            timeout: 20_000,
            message: 'triage audit entry was not applied within 20s',
          },
        );
        await auditApplied.toContain('Archive receipts');

        await page.goto(`${FRONTEND_BASE_URL}/rules?tab=history`, {
          waitUntil: 'domcontentloaded',
        });
        await page.getByRole('tab', { name: 'History' }).click();
        const auditRows = page.getByTestId('audit-table-row');
        await expect(auditRows.first()).toBeVisible({ timeout: 15_000 });
        await expect(auditRows.first()).toContainText(/Archive receipts|Archive|Label/);
      });

      await test.step('6. undo the triage action', async () => {
        const firstAuditRow = page.getByTestId('audit-table-row').first();
        await firstAuditRow.hover();
        await firstAuditRow.getByRole('button', { name: 'Undo' }).click();
        await page.getByRole('button', { name: 'Undo this action' }).click();
        const auditReverted = expect.poll(
          async () => {
            const response = await request.get('/api/triage/audit');
            if (!response.ok()) return false;
            const auditList = (await response.json()) as AuditListResponse;
            return (auditList.items ?? []).some(
              (entry) =>
                entry.gmailMessageId === seedMessageId &&
                entry.gmailThreadId === seedThreadId &&
                entry.ruleName === 'Archive receipts' &&
                entry.decisionState === 'REVERTED',
            );
          },
          { intervals: [500, 1000, 2000], timeout: 8000 },
        );
        await auditReverted.toBeTruthy();
      });

      await test.step('7. request AI draft from real backend endpoint', async () => {
        const draftResponse = await request.fetch(
          `/api/threads/${encodeURIComponent(seedThreadId)}/draft`,
          {
            method: 'POST',
          },
        );
        expect(draftResponse.ok()).toBeTruthy();
        const draftBody = await draftResponse.json();
        expect(draftBody.gmailThreadId).toBe(seedThreadId);
      });

      await test.step('8. confirm draft saved in stub Gmail with E2eStubChatModel text', async () => {
        const draftSaved = expect.poll(
          async () => {
            const response = await request.get(
              `/api/test/e2e-stub/drafts?messageId=${encodeURIComponent(seedMessageId)}`,
            );
            if (response.status() === 404) return null;
            if (!response.ok()) throw new Error(`unexpected status ${response.status()}`);
            const draft = (await response.json()) as DraftResponse;
            return draft.body ?? null;
          },
          {
            intervals: [500, 1000, 2000, 3000, 5000],
            timeout: 15_000,
            message: 'draft was not saved within 15s',
          },
        );
        await draftSaved.toContain(EXPECTED_DRAFT_TEXT);
      });

      await test.step('9. load analytics dashboard', async () => {
        await page.goto(`${FRONTEND_BASE_URL}/analytics`, { waitUntil: 'domcontentloaded' });
        await expect(page.getByRole('heading', { name: 'Analytics' })).toBeVisible({
          timeout: 15_000,
        });
        await expect(page.getByTestId('analytics-volume-panel')).toContainText(/Messages triaged/i);
      });

      await expectAppShellChrome(page, { sidebarVisible: true });
      await expectNoHorizontalOverflow(page);
    } finally {
      await page.close();
      await context.close();
      await request.dispose();
    }
  });
});

async function locatorIsVisible(locator: Locator): Promise<boolean> {
  return locator.isVisible().catch(() => false);
}

async function waitForLocatorVisible(locator: Locator, timeout: number): Promise<boolean> {
  return locator
    .waitFor({ state: 'visible', timeout })
    .then(() => true)
    .catch(() => false);
}

function numericHistoryIdFromUUID(value: string): string {
  return BigInt(`0x${value.replaceAll('-', '').slice(0, 12)}`).toString();
}
