apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://zeromail-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://zeromail-loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: "\"trace(?:Id|ID|_id)\":\"?([A-Fa-f0-9]{16,32})\"?"
          datasourceUid: tempo
          url: "$${__value.raw}"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://zeromail-tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
