#!/usr/bin/env bash
# FND-06 end-to-end verification: boot backend api against the shared dev DB
# tunnel, run codegen against the live /v3/api-docs, and grep the regenerated
# schema for every Phase 1 path. Exits non-zero on any failure. Always tears
# down api.
#
# Usage:
#   bash scripts/verify-codegen.sh
#
# Assumes:
#   - the SSH DB tunnel is up: localhost:5555 -> zeromail-postgres:5432
#     on the VPS dev database.
#   - local Redis is available on localhost:6379.
#   - pnpm 10.x is on PATH or accessible at $PNPM_BIN.
#   - gradlew works from the repo root.

set -euo pipefail

API_URL="${API_URL:-http://localhost:8080}"
SPEC_URL="${API_SPEC_URL:-${API_URL}/v3/api-docs}"
SCHEMA_OUT="apps/web/lib/api/schema.d.ts"
HEALTH_TIMEOUT_SEC="${HEALTH_TIMEOUT_SEC:-180}"
PNPM="${PNPM:-pnpm}"

cleanup() {
    if [[ -n "${API_PID:-}" ]] && kill -0 "$API_PID" 2>/dev/null; then
        echo "[verify-codegen] Stopping api pid=$API_PID"
        kill "$API_PID" 2>/dev/null || true
        wait "$API_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT

if [[ -f .env.local ]]; then
    set -a
    # shellcheck disable=SC1091
    source .env.local
    set +a
fi

DB_URL="${DB_URL:-jdbc:postgresql://localhost:5555/zeromail_dev?sslmode=disable}"
DB_USER="${DB_USER:-zeromail_dev}"
REDIS_HOST="${REDIS_HOST:-localhost}"
REDIS_PORT="${REDIS_PORT:-6379}"
if [[ -z "${DB_PASSWORD:-}" ]]; then
    echo "[verify-codegen] DB_PASSWORD is required. Put it in .env.local or export it." >&2
    exit 1
fi

echo "[verify-codegen] Starting backend api (bootRun) in background..."
# Phase 1 stub credentials so OAuth2 client autoconfig validates; the codegen path
# never actually contacts Google. AES-256 key is 32 zero bytes base64-encoded.
export GOOGLE_OAUTH_CLIENT_ID="${GOOGLE_OAUTH_CLIENT_ID:-verify-codegen-stub}"
export GOOGLE_OAUTH_CLIENT_SECRET="${GOOGLE_OAUTH_CLIENT_SECRET:-verify-codegen-stub}"
export REFRESH_TOKEN_KEY_BASE64="${REFRESH_TOKEN_KEY_BASE64:-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}"
./gradlew :backend:api:bootRun -q --args="--spring.datasource.url=${DB_URL} --spring.datasource.username=${DB_USER} --spring.datasource.password=${DB_PASSWORD} --spring.data.redis.host=${REDIS_HOST} --spring.data.redis.port=${REDIS_PORT}" >/tmp/verify-codegen-api.log 2>&1 &
API_PID=$!
echo "[verify-codegen] api pid=$API_PID; tailing health at ${API_URL}/actuator/health"

elapsed=0
until curl -fsS "${API_URL}/actuator/health" >/dev/null 2>&1; do
    if (( elapsed >= HEALTH_TIMEOUT_SEC )); then
        echo "[verify-codegen] api did not become healthy within ${HEALTH_TIMEOUT_SEC}s" >&2
        tail -n 200 /tmp/verify-codegen-api.log >&2 || true
        exit 1
    fi
    sleep 3
    elapsed=$((elapsed + 3))
done
echo "[verify-codegen] api healthy after ${elapsed}s"

echo "[verify-codegen] Running openapi codegen (SPEC_URL=${SPEC_URL})"
API_SPEC_URL="${SPEC_URL}" "$PNPM" -C apps/web generate:api

echo "[verify-codegen] Asserting generated schema contains Phase 1 paths"
REQUIRED_PATHS=(
    "/me"
    "/tenant/status"
    "/tenant/connect-gmail"
    "/tenant/disconnect"
    "/me/account"
    "/onboarding/select-template"
    "/onboarding/complete"
)
for p in "${REQUIRED_PATHS[@]}"; do
    if ! grep -q "\"$p\"" "${SCHEMA_OUT}"; then
        echo "[verify-codegen] MISSING path in generated schema: $p" >&2
        exit 1
    fi
done
if grep -q "regenerated by .pnpm generate:api." "${SCHEMA_OUT}"; then
    echo "[verify-codegen] schema.d.ts still contains placeholder stub header" >&2
    exit 1
fi
# openapi-typescript output always includes this header banner.
if ! grep -q "auto-generated by openapi-typescript" "${SCHEMA_OUT}"; then
    echo "[verify-codegen] schema.d.ts missing openapi-typescript banner" >&2
    exit 1
fi
echo "[verify-codegen] OK — FND-06 end-to-end verified"
