package com.zeromail.core.rules.catalog.usecases;

public enum RuleCatalogAuditAction {
    RULE_CATALOG_PERSONA_CREATED,
    RULE_CATALOG_PERSONA_UPDATED,
    RULE_CATALOG_PERSONA_ENABLED,
    RULE_CATALOG_PERSONA_DISABLED,
    RULE_CATALOG_PERSONAS_REORDERED,
    RULE_CATALOG_PROMPT_CREATED,
    RULE_CATALOG_PROMPT_UPDATED,
    RULE_CATALOG_PROMPT_ENABLED,
    RULE_CATALOG_PROMPT_DISABLED,
    RULE_CATALOG_PROMPTS_REORDERED,
    RULE_CATALOG_ACTION_DESCRIPTOR_UPSERTED,
    RULE_CATALOG_ACTION_DESCRIPTOR_ENABLED,
    RULE_CATALOG_ACTION_DESCRIPTOR_DISABLED,
    RULE_CATALOG_ACTION_DESCRIPTORS_REORDERED
}
