package com.zeromail.api.e2estub;

import com.zeromail.core.llm.usecases.LlmChatRequest;
import com.zeromail.core.llm.usecases.LlmChatResult;
import com.zeromail.core.llm.usecases.LlmModelClient;
import com.zeromail.core.llm.usecases.LlmUsage;
import com.zeromail.core.llm.usecases.RawToolCall;
import java.util.List;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.model.Generation;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Primary;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;

@Component
@Profile("e2e-stub")
@Primary
@ConditionalOnProperty(name = "zeromail.e2e-stub.enabled", havingValue = "true")
public class E2eStubChatModel implements ChatModel, LlmModelClient {

    public static final String CANNED_TEXT = "Hello tester — generated by E2eStubChatModel";

    @Override
    public ChatResponse call(Prompt prompt) {
        AssistantMessage.ToolCall saveDraftToolCall =
                new AssistantMessage.ToolCall(
                        "e2e-stub-save-draft",
                        "function",
                        "save_draft",
                        "{\"body\":\"" + CANNED_TEXT + "\"}");
        AssistantMessage assistantMessage =
                AssistantMessage.builder()
                        .content(CANNED_TEXT)
                        .toolCalls(List.of(saveDraftToolCall))
                        .build();
        return new ChatResponse(List.of(new Generation(assistantMessage)));
    }

    @Override
    public LlmChatResult call(LlmChatRequest request) {
        return new LlmChatResult(
                List.of(new RawToolCall("save_draft", "{\"body\":\"" + CANNED_TEXT + "\"}")),
                new LlmUsage(1, 1, "stop"));
    }

    @Override
    public Flux<ChatResponse> stream(Prompt prompt) {
        return Flux.just(call(prompt));
    }
}
